print('DAY-15')
print('-------')

bike=['pulsar','apache','r15','ninja','metero','mt15','interceptor']

print('task-01:(extend)')
print('----------------')
bike.extend(['himalayan','gt200'])
print(bike)
print()
print('Task-02:(append)')
print('----------------')
bike.append('pulsar')
print('bike=',bike)
print()
print('Task-03:(index wise display')
print('---------------------------')
index =bike.index('pulsar')
print('pulsar=' ,index)
index =bike.index('apache')
print('apache=' ,index)
index =bike.index('r15')
print('r15=' ,index)
index =bike.index('ninja')
print('ninja=' ,index)
index =bike.index('metero')
print('metero=' ,index)
index =bike.index('mt15')
print('mt15=' ,index)
index =bike.index('interceptor')
print('intercepter=' ,index)
print('pulser=',index)
print('')
print('Task-04:(pop)')
print('------------------------------------')
print('')
bike.pop(2)
print(bike)
print()
print('Tassk-05:(count duplication)')
print('----------------------------')
duplication = bike.count('pulsar')
print('duplication value is :',duplication)
print()
print('task-06:(sorting of value)')
print('--------------------------')
sorting = bike.sort()
print('sorting value is',sorting)
print()
print('Task-07:(reversing list )')
print('-----------------------')
print()
reversing = bike.reverse
print('reversing list :',bike)
print()
